# Generated by Django 4.1 on 2022-08-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0002_emailentry_timestamp_emailentry_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguroViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('telefone', models.TextField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('viagem', models.CharField(max_length=15)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('meio_transporte', models.CharField(max_length=25)),
                ('motivo_viagem', models.CharField(max_length=10)),
                ('data_ida', models.DateField()),
                ('data_volta', models.DateField()),
                ('viajantes_ate_64', models.IntegerField()),
                ('viajantes_65_mais', models.IntegerField()),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='EmailEntry',
        ),
    ]
