# Generated by Django 4.1 on 2022-08-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0003_seguroviagem_delete_emailentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguroviagem',
            name='telefone',
            field=models.CharField(max_length=25),
        ),
    ]
