# Generated by Django 4.1 on 2022-08-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0005_alter_seguroviagem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguroviagem',
            name='mensagem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seguroviagem',
            name='viajantes_65_mais',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seguroviagem',
            name='viajantes_ate_64',
            field=models.IntegerField(),
        ),
    ]
