# Generated by Django 4.1 on 2022-08-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0006_alter_seguroviagem_mensagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguroviagem',
            name='viajantes_65_mais',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seguroviagem',
            name='viajantes_ate_64',
            field=models.IntegerField(null=True),
        ),
    ]
