# Generated by Django 4.1 on 2022-08-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0007_alter_seguroviagem_viajantes_65_mais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguroviagem',
            name='data_ida',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='seguroviagem',
            name='data_volta',
            field=models.DateField(),
        ),
    ]
