# Generated by Django 4.1 on 2022-08-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0008_alter_seguroviagem_data_ida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguroviagem',
            name='data_ida',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='seguroviagem',
            name='data_volta',
            field=models.DateField(null=True),
        ),
    ]
