# Generated by Django 4.1 on 2022-09-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0009_alter_seguroviagem_data_ida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguroAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('comentario_gelo', models.CharField(blank=True, default='', max_length=2000)),
                ('data_envio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seguro Auto',
                'verbose_name_plural': 'Seguro Auto',
            },
        ),
        migrations.CreateModel(
            name='SeguroCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('comentario_gelo', models.CharField(blank=True, default='', max_length=2000)),
                ('data_envio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seguro Residencial',
                'verbose_name_plural': 'Seguro Residencial',
            },
        ),
        migrations.CreateModel(
            name='SeguroEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('comentario_gelo', models.CharField(blank=True, default='', max_length=2000)),
                ('data_envio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seguro Empresarial',
                'verbose_name_plural': 'Seguro Empresarial',
            },
        ),
        migrations.CreateModel(
            name='SeguroVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('comentario_gelo', models.CharField(blank=True, default='', max_length=2000)),
                ('data_envio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seguro Vida',
                'verbose_name_plural': 'Seguro Vida',
            },
        ),
    ]
